---
data:
  description: Automotive CentOS Stream 9 image manifest packages.
  labels:
  - automotive-c9s
  maintainer: micho
  repositories:
  - repository-c9s
  name: Automotive CentOS Stream 9 image manifest packages
  packages:
  - NetworkManager
  - NetworkManager-wifi
  - SDL2
  - abattis-cantarell-fonts
  - audit
  - bash
  - checkpolicy
  - chrony
  - cpp
  - dmidecode
  - dnf
  - dosfstools
  - dracut-config-generic
  - e2fsprogs
  - efibootmgr
  - firewalld
  - flashrom
  - flatpak
  - flatpak-selinux
  - flatpak-session-helper
  - fwupd-plugin-flashrom
  - gawk-all-langpacks
  - gdisk
  - gdm
  - glibc-gconv-extra
  - glibc-langpack-en
  - glibc-minimal-langpack
  - gnome-color-manager
  - gnome-control-center
  - gnome-remote-desktop
  - gnome-session-xsession
  - gnome-shell
  - gnome-terminal
  - greenboot
  - greenboot-grub2
  - greenboot-reboot
  - greenboot-rpm-ostree-grub2
  - greenboot-status
  - grub2-tools
  - grub2-tools-minimal
  - grubby
  - gzip
  - hostname
  - hunspell-en-GB
  - isomd5sum
  - iw
  - jasper-libs
  - kernel
  - kernel-modules
  - kernel-modules-extra
  - kernel-tools
  - langpacks-en
  - libappstream-glib
  - libatasmart
  - libblockdev
  - libblockdev-crypto
  - libblockdev-fs
  - libblockdev-loop
  - libblockdev-mdraid
  - libblockdev-part
  - libblockdev-swap
  - libblockdev-utils
  - libbytesize
  - libcap-ng-python3
  - libmng
  - libmpc
  - libstemmer
  - logrotate
  - lorax-templates-generic
  - mdadm
  - memstrack
  - nm-connection-editor
  - nss-altfiles
  - openal-soft
  - openssh-clients
  - openssh-server
  - openssl-pkcs11
  - p11-kit-server
  - passwd
  - pinentry
  - pinentry-gnome3
  - pipewire-alsa
  - pipewire-jack-audio-connection-kit
  - plymouth
  - plymouth
  - policycoreutils
  - policycoreutils-python-utils
  - polkit
  - protobuf-c
  - python-unversioned-command
  - python3
  - python3-audit
  - python3-iniparse
  - python3-libsemanage
  - python3-policycoreutils
  - python3-setools
  - python3-unbound
  - qemu-img
  - qt5-qt3d
  - qt5-qtbase
  - qt5-qtbase-common
  - qt5-qtbase-gui
  - qt5-qtdeclarative
  - qt5-qtgraphicaleffects
  - qt5-qtimageformats
  - qt5-qtmultimedia
  - qt5-qtquickcontrols
  - qt5-qtquickcontrols2
  - qt5-qtwayland
  - rng-tools
  - rootfiles
  - rpm-ostree
  - rpm-plugin-systemd-inhibit
  - rsyslog
  - selinux-policy-targeted
  - squashfs-tools
  - sudo
  - systemd
  - systemd-udev
  - tar
  - udisks2
  - unbound-libs
  - volume_key-libs
  - wireless-regdb
  - wpa_supplicant
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xfsprogs
  - xorriso
  - xz
  arch_packages:
    aarch64:
      - grub2-efi-aa64
      - grub2-efi-aa64-cdboot
      - shim-aa64
    x86_64:
      - grub2-efi-ia32-cdboot
      - grub2-efi-x64
      - grub2-efi-x64-cdboot
      - grub2-pc
      - grub2-pc-modules
      - grub2-tools-efi
      - grub2-tools-extra
      - microcode_ctl
      - shim-ia32
      - shim-x64
document: feedback-pipeline-workload
version: 1
 - 
